name: RAScript Audit
description: Compiles an RAScript for RetroAchievements development and performs an audit on the code.
author: joshraphael

inputs:
  game-id:
    description: "RetroAchievements game id"
    type: number
    required: true
  rascript:
    description: "The RAScript file name to compile (not including .rascript)"
    type: string
    required: true
  # report:
  #   description: "Create a report of the audit"
  #   type: boolean
  #   required: false
  # severity:
  #   description: "Level of severity to fail on"
  #   type: choice
  #   required: false
  #   options: 
  #     - info
  #     - warn
  #     - error

branding:
  color: blue
  icon: award

runs:
  using: 'composite'
  steps:
    - name: Set globals
      shell: bash
      run: |
        echo "GAME_ID=${{inputs.game-id}}" >> "${GITHUB_OUTPUT}"
        echo "RASCRIPT_FILE=${{inputs.rascript}}" >> "${GITHUB_OUTPUT}"
        echo "REPO_DIR=/app/rascript" >> "${GITHUB_OUTPUT}"
        echo "IMG_NAME=ghcr.io/joshraphael/rascript-audit-img:v0.0.1" >> "${GITHUB_OUTPUT}"
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Run rascript-audit
      shell: bash
      # uses: docker://ghcr.io/joshraphael/rascript-audit-img:v0.0.1
      run: |
        docker run -v "/var/run/docker.sock":"/var/run/docker.sock" --name rascript-audit -e GAME_ID=$GAME_ID -e REPO_DIR=$REPO_DIR -e RASCRIPT_FILE=$RASCRIPT_FILE --mount type=bind,src=.,dst=$REPO_DIR -it ghcr.io/joshraphael/rascript-audit-img:v0.0.1
    # - name: Test RAScript Audit
    #   shell: bash
    #   run: sh /app/entry.sh
    # - name: Test RAScript Audit2
    #   shell: bash
    #   working-directory: ${{env.CONTAINER_HOME}}
    #   run: ls
    # - name: Test RAScript Audit2
    #   shell: bash
    #   working-directory: ${{env.CONTAINER_HOME}}
    #   run: pwd