name: RAScript Audit
description: Compiles an RAScript for RetroAchievements development and performs an audit on the code.
author: joshraphael

inputs:
  game-id:
    description: "RetroAchievements game id"
    type: number
    required: true
  rascript:
    description: "The RAScript file name to compile"
    type: string
    required: true
  report:
    description: "Create a report of the audit"
    type: boolean
    required: false
  severity:
    description: "Level of severity to fail on"
    type: choice
    required: false
    options: 
      - info
      - warn
      - error

branding:
  color: blue
  icon: award

runs:
  using: 'composite'
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Run rascript-audit
      shell: bash
      run: |
        mkdir -p container_home
        docker run --name rascript-audit-img -e GAME_ID=${{ inputs.game-id }} -e RASCRIPT_FILE="${{ inputs.rascript }}" -e REPORT=${{ inputs.report }} -e SEVERITY=${{ inputs.severity }} --mount type=bind,src=.,dst=/app/rascript -i ghcr.io/joshraphael/rascript-audit-img:v0.0.3
        export CONTAINER_ID=$(docker ps -a --filter name=${{ inputs.name }} -q)
        docker cp $CONTAINER_ID:/app/home.txt container_home/
        docker cp $CONTAINER_ID:/app/copy.sh container_home/
        GAME_ID=${{ inputs.game-id }} bash container_home/copy.sh
    - name: Upload Achievement and Leaderboard Code
      uses: actions/upload-artifact@v4
      with:
        name: user-text
        path: container_home/${{ inputs.game-id }}-User.txt
    - name: Upload Code Notes
      uses: actions/upload-artifact@v4
      with:
        name: notes-json
        path: container_home/${{ inputs.game-id }}-Notes.json
    - name: Upload Rich Presence
      uses: actions/upload-artifact@v4
      with:
        name: rich-text
        path: container_home/${{ inputs.game-id }}-Rich.txt
    - name: Upload Report
      uses: actions/upload-artifact@v4
      if: ${{ inputs.report == 'true' }}
      with:
        name: report-text
        path: container_home/${{ inputs.game-id }}-Report.txt