name: RAScript Audit
description: Compiles an RAScript for RetroAchievements development and performs an audit on the code.
author: joshraphael

inputs:
  game-id:
    description: "RetroAchievements game id"
    type: number
    required: true
  rascript:
    description: "The RAScript file name to compile (not including .rascript)"
    type: string
    required: true
  report:
    description: "Create a report of the audit"
    type: boolean
    required: false
  severity:
    description: "Level of severity to fail on"
    type: choice
    required: false
    options: 
      - info
      - warn
      - error

branding:
  color: blue
  icon: award

runs:
  using: 'composite'
  steps:
    - name: Load docker imagedd
      uses: docker://ghcr.io/joshraphael/rascript-audit-img@71ce0e31e87c882e3c561eb1435b4fc26a8c63b1
    - name: Set ENV vars for home
      shell: bash
      run: echo "CONTAINER_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
    - name: Test RAScript Audit
      shell: bash
      run: sh /app/entry.sh
    - name: Test RAScript Audit2
      shell: bash
      working-directory: ${{env.CONTAINER_HOME}}
      run: ls
    - name: Test RAScript Audit2
      shell: bash
      working-directory: ${{env.CONTAINER_HOME}}
      run: pwd