name: Test action template file

on:
  push:
    branches:
      - '*'

permissions:
  contents: write
  pull-requests: write

jobs:
  template:
    name: template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check template is correct
        run: bash ./scripts/check.sh